theme: jekyll-theme-cayman
title: Crystal Engine
description: A Game Development Engine Written In C++
more_pages: true
view_on_github: true
home: https://percentboat4164.github.io/Illumination-Engine/
docs: https://percentboat4164.github.io/Illumination-Engine/docs/index.html
